version: '3'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: always
    environment:
      - BIND_ADDRESS=0.0.0.0
      - PORT=8080
      - BASE_URL=https://yourdomain.com/  # Update this with your domain
      - DEBUG=0
      - SETTINGS_PATH=/etc/searxng/settings.yml
    #ports:
    #  - "8012:8080"
    expose:
      - "8080"
    volumes:
      - /tmp/app2/searxng:/etc/searxng
    networks:
      - searxng_net

  filtron:
    image: dalf/filtron:latest
    container_name: filtron
    restart: always
    command: -listen 0.0.0.0:8012 -api 0.0.0.0:4041 -rules /etc/filtron/rules.json -target searxng:8080
    volumes:
      - $RULES_FOLDER/$RULES_FILE:/etc/filtron/rules.json
    networks:
      - searxng_net
    ports:
      - "8012:8012"

  morty:
    image: dalf/morty
    container_name: morty
    restart: always
    environment:
      - BIND_ADDRESS=0.0.0.0
      - PORT=3030
      - KEY=your_morty_key_here
    expose:
      - "3030"
    networks:
      - searxng_net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - searxng_net

networks:
  searxng_net:
    driver: bridge
